#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("app_pesquisa_analise.Droid.Resource", IsApplication=true)]

namespace app_pesquisa_analise.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::iTextSharpLGPLMonoForAndroid.Resource.String.library_name = global::app_pesquisa_analise.Droid.Resource.String.library_name;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::app_pesquisa_analise.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::app_pesquisa_analise.Droid.Resource.String.Hello;
			global::XamiTextSharpLGPL.Droid.Resource.String.library_name = global::app_pesquisa_analise.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int cellback = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CustomSelector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int download = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_chart_bar_white_36dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_chart_line_white_36dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_chart_pie_white_36dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_chart_timeline_white_36dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_clipboard_text_white_36dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_filter_grey600_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_format_annotation_plus_grey600_36dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_percent_grey600_36dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_settings_white_36dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_share_variant_white_36dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_undo_white_36dp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_weather_cloudy_grey600_36dp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_pesquisa_analise = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int minus = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int pesquisar = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int plus = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int sair = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int chart = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int imgBtnGrafico = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int titulo = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListViewCellGrafico = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
